Repository UQdeco2800/2021-ext-studio-2, pull requests merged in 2021-10, with the labels that each got.

#305 Add sound for enemies, Optimize the code structure, better spaceship attack
  source/core/assets/images/baozha.png
  source/core/assets/images/daodan.atlas
  source/core/assets/images/daodan.png
  source/core/assets/images/daodan_1.png
  source/core/assets/sounds/missile_explosion.mp3
  source/core/assets/sounds/monster_roar.mp3
  source/core/assets/sounds/spacecraft_floating.mp3
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/TouchAttackComponent.java
  source/core/src/main/com/deco2800/game/components/npc/SpaceshipAttackController.java
  source/core/src/main/com/deco2800/game/components/obstacle/MonsterDetails.java
  source/core/src/main/com/deco2800/game/components/obstacle/MonsterDispay.java
  source/core/src/main/com/deco2800/game/components/obstacle/ObstacleEventHandler.java
  source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/components/tasks/ObstacleAttackTask.java
  source/core/src/main/com/deco2800/game/entities/Entity.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/MonsterMenuScreen.java
  source/core/src/test/com/deco2800/game/components/obstacle/ObstacleEventHandlerTest.java
  source/core/src/test/com/deco2800/game/components/tasks/ObstacleAttackTaskTest.java
Labels: team-9, team-8

#306 Adding chapter art
  assets/artwork/story/chapter1art.png
  assets/artwork/story/chapter2art.png
  source/core/assets/images/story/chapter1art.png
  source/core/assets/images/story/chapter2art.png
Labels: task, team-7

#308 add bgms to screens
  source/core/assets/sounds/GameOver_bgm_final.mp3
  source/core/assets/sounds/History_Score_bgm.mp3
  source/core/assets/sounds/mainmenu_bgm.mp3
  source/core/assets/sounds/player_jump.mp3
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/score/DistanceDisplay.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
  source/core/src/main/com/deco2800/game/screens/GameOverScreen.java
  source/core/src/main/com/deco2800/game/screens/HistoryScoreScreen.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/MainMenuScreen.java
  source/core/src/main/com/deco2800/game/screens/MonsterMenuScreen.java
  source/core/src/main/com/deco2800/game/screens/PropsShopScreen.java
  source/core/src/main/com/deco2800/game/screens/SettingsScreen.java
Labels: task, team-9

#312 Prop Store updated
  source/core/assets/configs/propStore 2.json
  source/core/assets/configs/propStore.json
  source/core/src/main/com/deco2800/game/components/items/PropStoreDisplay.java
  source/core/src/main/com/deco2800/game/components/items/PropStoreGoldDisplay.java
  source/core/src/main/com/deco2800/game/components/items/PropStoreItemDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/PropStoreFactory.java
  source/core/src/main/com/deco2800/game/files/PropStoreRecord.java
  source/core/src/main/com/deco2800/game/screens/PropsShopScreen.java
Labels: enhancement, task, team-1

#327 Team9 sprint3 music&distance
  source/core/src/main/com/deco2800/game/services/DistanceService.java
Labels: team-9

#326 test(DateTimeUtils): fixed verbose date test which returned a differe…
  source/core/src/main/com/deco2800/game/utils/DateTimeUtils.java
  source/core/src/test/com/deco2800/game/utils/DateTimeUtilsTest.java
Labels: task, team-7

#336 Team9 sprint3 music&distance
  source/core/assets/sounds/track1.mp3
  source/core/assets/sounds/track2.mp3
  source/core/src/main/com/deco2800/game/components/score/DistanceDisplay.java
  source/core/src/test/com/deco2800/game/services/ScoreServiceTest.java
Labels: team-9

#325 implemented health prop functionality for prop store
  source/core/assets/configs/propStore.json
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/items/PropShopHelper.java
  source/core/src/main/com/deco2800/game/entities/configs/propStore/PropPropertyConfig.java
  source/core/src/main/com/deco2800/game/files/PropStoreRecord.java
Labels: enhancement, team-1

#347 add UI, test and sound component
  source/core/assets/images/explode.png
  source/core/assets/images/missile.atlas
  source/core/assets/images/missile.png
  source/core/assets/images/missiles.png
  source/core/assets/images/monkey_original.png
  source/core/assets/images/monster_menu/Facehugger_over.png
  source/core/assets/images/monster_menu/back.png
  source/core/assets/images/monster_menu/background.jpg
  source/core/assets/images/monster_menu/background.png
  source/core/assets/images/monster_menu/boss.png
  source/core/assets/images/monster_menu/box-background.png
  source/core/assets/images/monster_menu/box_covered.png
  source/core/assets/images/monster_menu/hugger.jpg
  source/core/assets/images/monster_menu/hugger.png
  source/core/assets/images/monster_menu/hugger_img.png
  source/core/assets/images/monster_menu/missile_over.png
  source/core/assets/images/monster_menu/monkey.jpg
  source/core/assets/images/monster_menu/monkey.png
  source/core/assets/images/monster_menu/monkey_img.png
  source/core/assets/images/monster_menu/monkey_original_over.png
  source/core/assets/images/monster_menu/plant.jpg
  source/core/assets/images/monster_menu/plant.png
  source/core/assets/images/monster_menu/plant_img.png
  source/core/assets/images/monster_menu/plant_over.png
  source/core/assets/images/monster_menu/ship.jpg
  source/core/assets/images/monster_menu/stone.jpg
  source/core/assets/images/monster_menu/stone.png
  source/core/assets/images/monster_menu/stone_img.png
  source/core/assets/images/monster_menu/stone_over.png
  source/core/assets/images/monster_menu/thorns.jpg
  source/core/assets/images/monster_menu/thorns.png
  source/core/assets/images/monster_menu/thorns_over.png
  source/core/assets/images/monster_menu/thron_img.png
  source/core/assets/images/monster_menu/ufo_img.png
  source/core/assets/images/monster_menu/ufo_over.png
  source/core/assets/images/portal.atlas
  source/core/assets/images/portal.png
  source/core/assets/images/spaceship.atlas
  source/core/assets/images/spaceships.png
  source/core/assets/images/tairport.atlas
  source/core/assets/images/ufo.png
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/SoundComponent.java
  source/core/src/main/com/deco2800/game/components/npc/SpaceshipAttackController.java
  source/core/src/main/com/deco2800/game/components/obstacle/MonsterDetails.java
  source/core/src/main/com/deco2800/game/components/obstacle/MonsterDispay.java
  source/core/src/main/com/deco2800/game/components/obstacle/ObstacleEventHandler.java
  source/core/src/main/com/deco2800/game/components/tasks/ObstacleAttackTask.java
  source/core/src/main/com/deco2800/game/entities/Entity.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/MonsterMenuScreen.java
  source/core/src/test/com/deco2800/game/components/SoundComponentTest.java
  source/core/src/test/com/deco2800/game/components/npc/SpaceshipAttackControllerTest.java
  source/core/src/test/com/deco2800/game/components/obstacle/ObstacleEventHandlerTest.java
  source/core/src/test/com/deco2800/game/components/tasks/ObstacleAttackTaskTest.java
Labels: team-8

#349 add javadoc and logger
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/npc/SpaceshipAttackController.java
  source/core/src/main/com/deco2800/game/components/obstacle/MonsterDetails.java
  source/core/src/main/com/deco2800/game/components/obstacle/MonsterDispay.java
  source/core/src/main/com/deco2800/game/components/obstacle/ObstacleEventHandler.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/MonsterMenuScreen.java
Labels: team-8

#351 chore(SonarCloud): sonar cloud code smells and bug fixes
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/AchievementRecordsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/ChapterDisplay.java
  source/core/src/main/com/deco2800/game/components/score/ScoreDetailsDialog.java
  source/core/src/main/com/deco2800/game/components/score/ScoreHistoryDisplay.java
  source/core/src/main/com/deco2800/game/files/GameInfo.java
  source/core/src/main/com/deco2800/game/files/GameRecords.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
  source/core/src/main/com/deco2800/game/screens/HistoryScoreScreen.java
  source/core/src/test/com/deco2800/game/files/GameInfoTest.java
Labels: task, team-7

#350 Team1 prop shop implemented unit testing
  source/core/src/main/com/deco2800/game/components/items/ItemComponent.java
  source/core/src/main/com/deco2800/game/components/items/PropShopHelper.java
  source/core/src/main/com/deco2800/game/components/items/PropStoreDisplay.java
  source/core/src/main/com/deco2800/game/components/items/PropStoreGoldDisplay.java
  source/core/src/main/com/deco2800/game/components/items/PropStoreItemDisplay.java
  source/core/src/main/com/deco2800/game/files/PropStoreRecord.java
  source/core/src/test/com/deco2800/game/components/Items/ItemComponentTest.java
  source/core/src/test/com/deco2800/game/components/Items/PropShopHelperTest.java
Labels: enhancement, team-1

#353 242 spaceship boss
  source/core/src/main/com/deco2800/game/components/npc/SpaceshipAttackController.java
Labels: team-8

#359 add javadoc for sound component
  source/core/src/main/com/deco2800/game/components/SoundComponent.java
Labels: team-8

#371 feat(Achievements): added bonus gold on achievement
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsHelper.java
  source/core/src/main/com/deco2800/game/components/player/InventoryComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
Labels: task, team-7

#395 Player attack
  source/core/assets/images/particle/Particle.party
  source/core/assets/images/particle/test.jpg
  source/core/assets/images/particle/test.party
  source/core/assets/images/particle/weapon.party
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/obstacle/ObstacleEventHandler.java
  source/core/src/main/com/deco2800/game/entities/Entity.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/deco2800/game/rendering/ParticleRenderComponent.java
  source/core/src/test/com/deco2800/game/entities/EntityTest.java
Labels: team-8

#398 Added music chooser GUI assets
  assets/artwork/settings/musicSelectionButton.png
  assets/artwork/settings/musicSelectionDialog.png
  assets/artwork/settings/radioButtonOff.png
  assets/artwork/settings/radioButtonOn.png
  source/core/assets/settings/musicSelectionButton.png
  source/core/assets/settings/musicSelectionDialog.png
  source/core/assets/settings/radioButtonOff.png
  source/core/assets/settings/radioButtonOn.png
Labels: task, team-7

#400 Team7 chooser GUI
  source/core/assets/images/settings/fps.png
  source/core/assets/images/settings/fpsOff.png
  source/core/assets/images/settings/fullScreen.png
  source/core/assets/images/settings/fullScreenOff.png
  source/core/assets/images/settings/musicSelectionButton.png
  source/core/assets/images/settings/musicSelectionDialog.png
  source/core/assets/images/settings/radioButtonOff.png
  source/core/assets/images/settings/radioButtonOn.png
  source/core/assets/images/settings/resolution.png
  source/core/assets/images/settings/resolutionOff.png
  source/core/assets/images/settings/settingsBackground1.png
  source/core/assets/images/settings/settingsBackground2.png
  source/core/assets/images/settings/settingsBackground3.png
  source/core/assets/images/settings/uiScale.png
  source/core/assets/images/settings/uiScaleOff.png
  source/core/assets/images/settings/vsync.png
  source/core/assets/images/settings/vsyncOff.png
  source/core/src/main/com/deco2800/game/components/BackgroundSelectionComponent.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
Labels: task, team-7

#419 Adding chapter art
  assets/artwork/story/chapter3art.png
  assets/artwork/story/chapter4art.png
  assets/artwork/story/chapter5art.png
  source/core/assets/images/chapter3art.png
  source/core/assets/images/chapter4art.png
  source/core/assets/images/story/chapter5art.png
Labels: team-7

#440 Refactored GameInfo, GameRecords and orchestrated some logic into GameRecordUtils, Added some javadoc, Minor codebase cleanup
  source/core/src/main/com/deco2800/game/components/BackgroundSelectionComponent.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/AchievementRecordsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/ChapterDisplay.java
  source/core/src/main/com/deco2800/game/components/gameover/GameOverDisplay.java
  source/core/src/main/com/deco2800/game/components/score/ScoreDetailsDialog.java
  source/core/src/main/com/deco2800/game/components/score/ScoreHistoryDisplay.java
  source/core/src/main/com/deco2800/game/files/PropStoreRecord.java
  source/core/src/main/com/deco2800/game/files/meta/BackgroundMusic.java
  source/core/src/main/com/deco2800/game/files/meta/GameInfo.java
  source/core/src/main/com/deco2800/game/files/stats/GameChapters.java
  source/core/src/main/com/deco2800/game/files/stats/GameRecordUtils.java
  source/core/src/main/com/deco2800/game/files/stats/GameRecords.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
  source/core/src/main/com/deco2800/game/screens/BuffManualMenuScreen.java
  source/core/src/main/com/deco2800/game/screens/GameOverScreen.java
  source/core/src/main/com/deco2800/game/screens/HistoryScoreScreen.java
  source/core/src/main/com/deco2800/game/screens/InstructionsScreen.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/MonsterMenuScreen.java
  source/core/src/main/com/deco2800/game/screens/PropsShopScreen.java
  source/core/src/main/com/deco2800/game/screens/SettingsScreen.java
  source/core/src/main/com/deco2800/game/screens/UnlockedAttiresScreen.java
  source/core/src/test/com/deco2800/game/files/GameChaptersTest.java
  source/core/src/test/com/deco2800/game/files/GameInfoTest.java
Labels: enhancement, task, team-7

#442 feat(settings screen,music selection):added music selection chooser g…
  source/core/assets/configs/backgroundMusic.json
  source/core/assets/sounds/customBgm/bgmMainGame1.mp3
  source/core/assets/sounds/customBgm/bgmMainGame2.mp3
  source/core/src/main/com/deco2800/game/components/BackgroundSelectionComponent.java
  source/core/src/main/com/deco2800/game/components/settingsmenu/SettingsMenuDisplay.java
  source/desktop/build.gradle
Labels: task, team-7

#444 test(GameRecordUtils): Tests added for commonly used methods
  source/core/src/test/com/deco2800/game/files/GameRecordUtilsTest.java
  source/core/src/test/com/deco2800/game/files/GameRecordsTest.java
Labels: enhancement, task, team-7

#446 Team9 sprint4 code smell fix
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/ItemBar/ItemBarDisplay.java
  source/core/src/main/com/deco2800/game/components/ItemBar/newItembar.java
  source/core/src/main/com/deco2800/game/components/buff/Buff.java
  source/core/src/main/com/deco2800/game/components/buff/BuffDescriptionDisplay.java
  source/core/src/main/com/deco2800/game/components/buff/BuffDisplay.java
  source/core/src/main/com/deco2800/game/components/buff/DeBuff.java
  source/core/src/main/com/deco2800/game/components/foodAndwater/CountWaterSystem.java
  source/core/src/main/com/deco2800/game/components/foodAndwater/FoodDisplay.java
  source/core/src/main/com/deco2800/game/components/foodAndwater/RecycleDisplay.java
  source/core/src/main/com/deco2800/game/components/foodAndwater/WaterDisplay.java
  source/core/src/main/com/deco2800/game/components/gamearea/GameAreaDisplay.java
  source/core/src/main/com/deco2800/game/components/items/InventorySystem.java
  source/core/src/main/com/deco2800/game/components/items/ItemBar.java
  source/core/src/main/com/deco2800/game/components/items/ItemComponent.java
  source/core/src/main/com/deco2800/game/components/items/PropShopHelper.java
  source/core/src/main/com/deco2800/game/components/items/PropStoreDisplay.java
  source/core/src/main/com/deco2800/game/components/items/PropStoreGoldDisplay.java
  source/core/src/main/com/deco2800/game/components/items/PropStoreItemDisplay.java
  source/core/src/main/com/deco2800/game/components/items/PropsShopDisplay.java
  source/core/src/main/com/deco2800/game/components/items/TestBuffForItem.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameActions.java
  source/core/src/main/com/deco2800/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/components/npc/SpaceshipAttackController.java
  source/core/src/main/com/deco2800/game/components/obstacle/ObstacleEventHandler.java
  source/core/src/main/com/deco2800/game/components/player/Bag.java
  source/core/src/main/com/deco2800/game/components/player/PlayerActions.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/deco2800/game/components/player/TouchPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/components/player/UnlockedAttiresDisplay.java
  source/core/src/main/com/deco2800/game/components/score/DistanceDisplay.java
  source/core/src/main/com/deco2800/game/components/score/ScoreDisplay.java
  source/core/src/main/com/deco2800/game/components/score/ScoringSystemV1.java
  source/core/src/main/com/deco2800/game/services/DistanceService.java
  source/core/src/test/com/deco2800/game/files/UserScoreHistoryTest.java
  source/core/src/test/com/deco2800/game/services/ScoreServiceTest.java
Labels: task, team-9

#457 bug(PropsShopScreen): background music playing even after screen exit
  source/core/src/main/com/deco2800/game/screens/PropsShopScreen.java
Labels: bug, task, team-7

#479 added poison in DeBuff along with test
  source/core/src/main/com/deco2800/game/components/buff/DeBuff.java
  source/core/src/main/com/deco2800/game/components/obstacle/ObstacleEventHandler.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/deco2800/game/components/buff/DeBuffComponentTest.java
Labels: task, team-5
