Repository UQdeco2800/2021-ext-studio-2, pull requests merged in 2021-08, with the labels that each got.

#59 Achievement list and conditions
  source/core/assets/configs/achieve.json
  source/core/assets/images/achievements/bronze game-breaker.png
  source/core/assets/images/achievements/bronze tool master.png
  source/core/assets/images/achievements/bronze veteran.png
  source/core/assets/images/achievements/gameBreakerBronze.png
  source/core/assets/images/achievements/gameBreakerGold.png
  source/core/assets/images/achievements/gameBreakerSilver.png
  source/core/assets/images/achievements/gold game-breaker (3).png
  source/core/assets/images/achievements/gold tool master (3).png
  source/core/assets/images/achievements/gold veteran.png
  source/core/assets/images/achievements/sliver game-breaker.png
  source/core/assets/images/achievements/sliver tool master.png
  source/core/assets/images/achievements/sliver veteran.png
  source/core/assets/images/achievements/toolMasterBronze.png
  source/core/assets/images/achievements/toolMasterGold.png
  source/core/assets/images/achievements/toolMasterSilver.png
  source/core/assets/images/achievements/veteranBronze.png
  source/core/assets/images/achievements/veteranGold.png
  source/core/assets/images/achievements/veteranSilver.png
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/entities/configs/AchievementConfigs.java
  source/core/src/main/com/deco2800/game/entities/configs/achievements/BaseAchievementConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/achievements/ConditionConfig.java
  source/core/src/main/com/deco2800/game/entities/factories/AchievementFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
Labels: task, team-7

#69 Team1: added first aid item, testbuff for first aid , and itempickup event
  source/core/assets/images/Items/first_aid_kit.png
  source/core/assets/images/Items/food.png
  source/core/assets/images/Items/water.png
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/Obstacle/ObstacleDispare.java
  source/core/src/main/com/deco2800/game/components/items/FirstAidFunction.java
  source/core/src/main/com/deco2800/game/components/items/TestBuffForItem.java
  source/core/src/main/com/deco2800/game/entities/factories/ItemFactory.java
Labels: task, team-1

#82 test(achievements): added AchievementStatsComponent validation tests
  source/core/src/test/com/deco2800/game/components/achievements/AchievementStatsComponentTest.java
  source/core/src/test/com/deco2800/game/components/tasks/ChaseTaskTest.java
Labels: task, team-7

#85 feat(AchievementsStatsComponent, Concurrency): Created Async Task Queue
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
  source/core/src/main/com/deco2800/game/concurrency/AsyncTaskQueue.java
Labels: task, team-7

#78 Team1 items_ Implementing Unit Testing
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/items/FirstAidComponent.java
  source/core/src/main/com/deco2800/game/components/items/TestBuffForItem.java
  source/core/src/main/com/deco2800/game/components/player/Bag.java
  source/core/src/main/com/deco2800/game/entities/factories/ItemFactory.java
  source/core/src/test/com/deco2800/game/components/Items/FirstAidComponentTest.java
  source/gradle/wrapper/gradle-wrapper.properties
Labels: team-1

#89 chore(achievements): ignore thread sleep interrupt log
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
Labels: task, team-7

#90 Wiki assets
  assets/wiki/achievements/seq_display.png
  assets/wiki/achievements/seq_health.png
  assets/wiki/achievements/seq_item_pickup.png
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
  source/core/src/main/com/deco2800/game/entities/configs/achievements/BaseAchievementConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/achievements/ConditionConfig.java
Labels: documentation, task, team-7

#93 Add class diagram via upload
  assets/wiki/achievements/AchievementClassDiagram.png
Labels: documentation, task, team-7
