Repository UQdeco2800/2021-ext-studio-2, pull requests merged in 2021-09, with the labels that each got.

#143 Added bonus background image
  assets/artwork/achievements/bonusBg.png
Labels: team-7

#149 Added bonus sound asset
  assets/artwork/achievements/achievementSound.wav
Labels: task, team-7

#150 add achievement cards for new achievements
  assets/artwork/achievements/healerBronze.png
  assets/artwork/achievements/healerGold.png
  assets/artwork/achievements/healerSilver.png
  assets/artwork/achievements/masterBronze.png
  assets/artwork/achievements/masterGold.png
  assets/artwork/achievements/masterSilver.png
  assets/artwork/achievements/strangerBronze.png
  assets/artwork/achievements/strangerGold.png
  assets/artwork/achievements/strangerSilver.png
Labels: task, team-7

#137 Achievements - Enhancement
  source/core/assets/images/achievements/bonusBg.png
  source/core/assets/sounds/achievementSound.wav
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsHelper.java
  source/core/src/main/com/deco2800/game/components/score/ScoreDisplay.java
Labels: enhancement, task, team-9, team-7

#154 Added new achievements, Minor under the hood changes
  source/core/assets/configs/achieve.json
  source/core/assets/images/achievements/healerBronze.png
  source/core/assets/images/achievements/healerGold.png
  source/core/assets/images/achievements/healerSilver.png
  source/core/assets/images/achievements/masterBronze.png
  source/core/assets/images/achievements/masterGold.png
  source/core/assets/images/achievements/masterSilver.png
  source/core/assets/images/achievements/strangerBronze.png
  source/core/assets/images/achievements/strangerGold.png
  source/core/assets/images/achievements/strangerSilver.png
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsHelper.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/components/items/FirstAidComponent.java
  source/core/src/main/com/deco2800/game/entities/configs/achievements/ConditionConfig.java
  source/core/src/test/com/deco2800/game/components/achievements/AchievementStatsComponentTest.java
Labels: task, team-7

#165 Added game story draft JSON file
  source/core/assets/configs/story.json
Labels: task, team-7

#166 feature(achievements):added unit tests for additional achievements
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/test/com/deco2800/game/components/achievements/AchievementStatsComponentTest.java
Labels: task, team-7

#168 Added achievement screen background
  source/core/assets/images/achievements/achievementBackground.png
Labels: task, team-7

#152 Game Metadata, Achievements Screen
  source/core/assets/configs/achievements.json
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/AchievementRecordsDisplay.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/concurrency/AsyncTaskQueue.java
  source/core/src/main/com/deco2800/game/entities/configs/AchievementConfigs.java
  source/core/src/main/com/deco2800/game/entities/configs/achievements/BaseAchievementConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/achievements/ConditionConfig.java
  source/core/src/main/com/deco2800/game/entities/factories/AchievementFactory.java
  source/core/src/main/com/deco2800/game/files/AchievementRecords.java
  source/core/src/main/com/deco2800/game/files/GameInfo.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: task, team-7

#169 Achievements Screen UI
  source/core/assets/configs/story.json
  source/core/assets/images/achievements/crossButton.png
  source/core/assets/images/story/chapter1.png
  source/core/assets/images/story/chapter2.png
  source/core/assets/images/story/chapter3.png
  source/core/assets/images/story/chapter4.png
  source/core/assets/images/story/chapter5.png
  source/core/assets/images/story/chapterLink.png
  source/core/assets/images/story/chapterLock.png
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/AchievementRecordsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/ChapterDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/AchievementFactory.java
  source/core/src/main/com/deco2800/game/files/AchievementRecords.java
  source/core/src/main/com/deco2800/game/files/GameChapters.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
Labels: task, team-7

#183 chapter UI
  source/core/assets/images/story/chapterDialog.png
  source/core/src/main/com/deco2800/game/components/achievements/screen/ChapterDisplay.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
Labels: enhancement, task, team-7

#182 JvmArgs based on Operating System
  source/desktop/build.gradle
Labels: bug, team-7

#188 Make ScoreService accessible through ServiceLocator
  source/core/src/main/com/deco2800/game/components/score/ScoreDisplay.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/services/ScoreService.java
  source/core/src/main/com/deco2800/game/services/ServiceLocator.java
Labels: enhancement, team-9

#201 update ScoreService and bag bonus
  source/core/src/main/com/deco2800/game/components/player/Bag.java
  source/core/src/main/com/deco2800/game/services/ScoreService.java
Labels: documentation, enhancement, team-9

#192 Team 7 - Game Count, Game Chapters tests
  source/.gitignore
  source/core/src/main/com/deco2800/game/files/AchievementRecords.java
  source/core/src/main/com/deco2800/game/files/GameChapters.java
  source/core/src/main/com/deco2800/game/files/GameInfo.java
  source/core/src/test/com/deco2800/game/files/GameChaptersTest.java
  source/core/src/test/com/deco2800/game/files/GameInfoTest.java
Labels: task, team-7

#205 105 active attacker
  source/core/assets/images/Facehugger.atlas
  source/core/assets/images/Facehugger.png
  source/core/assets/images/Facehugger_1.png
  source/core/assets/images/face_resize.png
  source/core/assets/images/monkey.atlas
  source/core/assets/images/monkey.png
  source/core/src/main/com/deco2800/game/components/Obstacle/ObstacleDisappear.java
  source/core/src/main/com/deco2800/game/components/tasks/ObstacleAttackTask.java
  source/core/src/main/com/deco2800/game/entities/Entity.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/test/com/deco2800/game/components/obstacle/ObstacleDisappearTest.java
  source/core/src/test/com/deco2800/game/components/tasks/ChaseTaskTest.java
  source/core/src/test/com/deco2800/game/components/tasks/ObstacleAttackTaskTest.java
  source/core/src/test/com/deco2800/game/entities/EntityTest.java
Labels: team-8

#206 Assets redesigned achievement background
  source/core/assets/images/achievements/achievementBackground.png
Labels: task, team-7

#207 Team1 items
  source/core/assets/gold.txt
  source/core/assets/images/Items/bandage.png
  source/core/assets/images/Items/goldCoin.png
  source/core/assets/images/Items/props/add_food.png
  source/core/assets/images/Items/props/add_health.png
  source/core/assets/images/Items/props/add_water.png
  source/core/assets/images/Items/props/shield.png
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsBonusItems.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/components/items/FirstAidFunction.java
  source/core/src/main/com/deco2800/game/components/items/GoldComponent.java
  source/core/src/main/com/deco2800/game/components/items/ItemComponent.java
  source/core/src/main/com/deco2800/game/components/items/PropsShopDisplay.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/components/player/InventoryComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/deco2800/game/entities/Entity.java
  source/core/src/main/com/deco2800/game/entities/factories/ItemFactory.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/MainMenuScreen.java
  source/core/src/main/com/deco2800/game/screens/PropsShopScreen.java
  source/core/src/test/com/deco2800/game/components/Items/AchievementBonusItemTest.java
  source/core/src/test/com/deco2800/game/components/Items/GoldComponentTest.java
  source/core/src/test/com/deco2800/game/components/Items/ItemComponentTest.java
Labels: team-1

#208 The history score board feature finished
  source/core/src/main/com/deco2800/game/components/score/HistoryScoreDisplay.java
Labels: feature, team-9

#210 Team 4 main player character
  source/core/assets/gold.txt
  source/core/assets/images/mpc/MPC_Animation.png
  source/core/assets/images/mpc/mpc_atlas_workspace/MPC_Animation.atlas
  source/core/assets/images/mpc/mpc_atlas_workspace/MPC_Animation.png
  source/core/assets/test/files/mpcAnimation.atlas
  source/core/assets/test/files/mpcAnimation.png
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/items/GoldComponent.java
  source/core/src/main/com/deco2800/game/components/items/ItemComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
  source/core/src/test/com/deco2800/game/components/player/PlayerAnimationAtlasTest.java
Labels: feature, team-4

#214 Achievement Background
  assets/artwork/achievements/achievementBackground.png
Labels: task, team-7

#217 build(game, desktop.gradle): append jvmArgs based on the operating sy…
  source/desktop/build.gradle
Labels: bug

#219 Questionnaire-Achievement Enhancement User Testing
  assets/wiki/achievements/Ques1.png
  assets/wiki/achievements/Ques2.png
  assets/wiki/achievements/Ques3.png
  assets/wiki/achievements/Ques4.png
Labels: team-7

#223 Update Entity.java
  source/core/src/main/com/deco2800/game/entities/Entity.java
Labels: team-8

#222 Team7 minor revisions
  assets/artwork/achievements/bonusBg.png
  source/core/assets/configs/achievements.json
  source/core/assets/configs/story.json
  source/core/assets/images/achievements/bonusBg.png
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/AchievementRecordsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/ChapterDisplay.java
  source/core/src/main/com/deco2800/game/files/GameRecords.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
  source/core/src/test/com/deco2800/game/components/achievements/AchievementStatsComponentTest.java
Labels: team-7

#224 wiki(Achievements, Assets): Added palette for screen
  assets/wiki/achievements/conceptAchievementsScreen.png
  assets/wiki/achievements/palette_1.png
  assets/wiki/achievements/palette_2.png
  assets/wiki/achievements/palette_screen_1.png
  assets/wiki/achievements/palette_screen_2.png
Labels: documentation, task, team-7

#225 bug(Bonus popup): bonus font color fix
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
Labels: bug, task, team-7

#226 Inventory system and item bar beta
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/items/InventorySystem.java
  source/core/src/main/com/deco2800/game/components/items/ItemBar.java
  source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/entities/factories/ItemFactory.java
  source/core/src/main/com/deco2800/game/input/InputComponent.java
  source/core/src/main/com/deco2800/game/input/InputDecorator.java
Labels: feature, team-5

#243 Scoring service migration, fixed game over screen score bug.
  source/.gitignore
  source/core/assets/gold.txt
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/components/gameover/GameOverDisplay.java
  source/core/src/main/com/deco2800/game/files/GameRecords.java
  source/core/src/main/com/deco2800/game/services/ScoreService.java
Labels: bug, task, team-9, team-7

#254 Team7 history screen
  source/core/src/main/com/deco2800/game/components/achievements/screen/AchievementRecordsDisplay.java
  source/core/src/main/com/deco2800/game/components/score/ScoreDetailsDialog.java
  source/core/src/main/com/deco2800/game/components/score/ScoreHistoryDisplay.java
  source/core/src/main/com/deco2800/game/files/GameRecords.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
  source/core/src/main/com/deco2800/game/screens/HistoryScoreScreen.java
  source/core/src/main/com/deco2800/game/utils/DateTimeUtils.java
Labels: enhancement, task, team-7

#257 242 spaceship boss
  source/core/assets/configs/NPCs.json
  source/core/assets/images/portal.png
  source/core/assets/images/rocket-ship-launch.png
  source/core/assets/images/show.jpg
  source/core/assets/images/ufo.png
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/Obstacle/ObstacleDisappear.java
  source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/entities/Entity.java
  source/core/src/main/com/deco2800/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: team-8

#259 Print character coordinates when entering the new map, for the new ma…
  source/core/src/main/com/deco2800/game/components/Obstacle/ObstacleDisappear.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: team-8

#266 Team7 scoreboard details
  assets/artwork/achievements/achievementStatusBronze.png
  assets/artwork/achievements/achievementStatusGold.png
  assets/artwork/achievements/achievementStatusNone.png
  assets/artwork/achievements/achievementStatusSilver.png
  assets/artwork/achievements/trophyDialogSilver.png
  source/core/assets/images/achievements/achievementStatusBronze.png
  source/core/assets/images/achievements/achievementStatusGold.png
  source/core/assets/images/achievements/achievementStatusNone.png
  source/core/assets/images/achievements/achievementStatusSilver.png
  source/core/assets/images/achievements/trophyDialogSilver.png
  source/core/src/main/com/deco2800/game/components/score/ScoreDetailsDialog.java
  source/core/src/main/com/deco2800/game/components/score/ScoreHistoryDisplay.java
  source/core/src/main/com/deco2800/game/screens/HistoryScoreScreen.java
Labels: enhancement, task, team-7

#268 Create Achievement screen bgm for team 7
  source/core/assets/sounds/achievementBgm.mp3
  source/core/src/main/com/deco2800/game/components/BackgroundSoundComponent.java
  source/core/src/main/com/deco2800/game/screens/AchievementsScreen.java
Labels: enhancement, task, team-9, team-7

#269 Added important achievement events
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsDisplay.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsHelper.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/components/score/ScoreDisplay.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: enhancement, task, team-4, team-7, team-1

#278 237 monster manual
  source/core/assets/images/monster_menu/Monsterbox.jpg
  source/core/assets/images/monster_menu/back.png
  source/core/assets/images/monster_menu/background.png
  source/core/assets/images/monster_menu/secret.jpg
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/components/Obstacle/MonsterDetails.java
  source/core/src/main/com/deco2800/game/components/Obstacle/MonsterDispay.java
  source/core/src/main/com/deco2800/game/components/Obstacle/ObstacleDisappear.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/components/tasks/ObstacleAttackTask.java
  source/core/src/main/com/deco2800/game/screens/monsterMenuScreen.java
Labels: team-8

#285 test(DateTimeUtils): tested date time utils class logic
  source/core/src/main/com/deco2800/game/utils/DateTimeUtils.java
  source/core/src/test/com/deco2800/game/utils/DateTimeUtilsTest.java
Labels: task, team-7

#288 Adding 2 new achievements, Bonus item improvements
  source/core/assets/configs/achievements.json
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsBonusItems.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsHelper.java
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/components/items/GoldComponent.java
  source/core/src/main/com/deco2800/game/components/score/ScoreDetailsDialog.java
  source/core/src/main/com/deco2800/game/entities/configs/achievements/ConditionConfig.java
  source/core/src/main/com/deco2800/game/entities/factories/AchievementFactory.java
  source/core/src/main/com/deco2800/game/screens/HistoryScoreScreen.java
Labels: task, team-7, team-1

#290 New Achievements Testing (game fanatic, collector)
  source/core/src/test/com/deco2800/game/components/achievements/AchievementStatsComponentTest.java
Labels: task, team-7

#292 Team9 sprint3 music&distance
  source/core/assets/images/distanceboard.png
  source/core/src/main/com/deco2800/game/components/gameover/GameOverDisplay.java
  source/core/src/main/com/deco2800/game/components/score/DistanceDisplay.java
  source/core/src/main/com/deco2800/game/components/score/ScoreDetailsDialog.java
  source/core/src/main/com/deco2800/game/components/score/ScoreDisplay.java
  source/core/src/main/com/deco2800/game/files/GameRecords.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/services/DistanceService.java
  source/core/src/main/com/deco2800/game/services/ScoreService.java
  source/core/src/main/com/deco2800/game/services/ServiceLocator.java
  source/core/src/test/com/deco2800/game/services/ScoreServiceTest.java
Labels: enhancement, task, team-9, team-7

#293 Team7 scoreboard assets
  assets/artwork/achievements/calenderIcon.png
  assets/artwork/achievements/scoreIcon.png
  assets/artwork/achievements/timeIcon.png
  source/core/assets/images/achievements/calenderIcon.png
  source/core/assets/images/achievements/scoreIcon.png
  source/core/assets/images/achievements/timeIcon.png
Labels: task, team-7

#295 Fix some bugs
  source/core/assets/images/launch.png
  source/core/assets/images/ufo.png
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/Obstacle/ObstacleDisappear.java
  source/core/src/main/com/deco2800/game/entities/Entity.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/deco2800/game/physics/PhysicsLayer.java
  source/core/src/main/com/deco2800/game/physics/components/ColliderComponent.java
  source/core/src/main/com/deco2800/game/rendering/RenderComponent.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: team-6, team-8

#298 added alphamineron achievement assets
  assets/artwork/achievements/alphamineron.png
  assets/artwork/achievements/alphamineronTrophy.png
  source/core/assets/images/achievements/alphamineron.png
  source/core/assets/images/achievements/alphamineronTrophy.png
Labels: task, team-7

#300 feat(achievement integrations): New Achievements conditions
  source/core/assets/configs/achievements.json
  source/core/assets/images/achievements/alphamineronGold.png
  source/core/assets/images/achievements/alphamineronGoldTrophy.png
  source/core/src/main/com/deco2800/game/components/achievements/AchievementsStatsComponent.java
  source/core/src/main/com/deco2800/game/components/achievements/screen/AchievementRecordsDisplay.java
  source/core/src/main/com/deco2800/game/entities/configs/achievements/ConditionConfig.java
  source/core/src/test/com/deco2800/game/components/achievements/AchievementStatsComponentTest.java
  source/core/src/test/com/deco2800/game/files/GameChaptersTest.java
  source/core/src/test/com/deco2800/game/files/GameInfoTest.java
Labels: enhancement, task, team-7
